In [1]:
from gym_tradebi.dataloader.json import Dataloader
import numpy as np
import pandas as pd

In [2]:
source = Dataloader('../history/EUR_USD_H1_history.json')

In [3]:
d = source.getData()

In [4]:
list(d.columns.values)

['Open', 'High', 'Low', 'Close', 'Volume']

In [9]:
d.values[0]

array([1.16994e+00, 1.16996e+00, 1.16675e+00, 1.16738e+00, 4.81300e+03])

In [8]:
d['Open'].iloc[0]

1.16994

In [6]:
high = np.array([])
y = np.array(["x"])
array_3 = np.append(high, y)
array_3

array(['x'], dtype='<U32')

In [7]:
for x in list(d.columns.values):
    high = np.append(high,np.array([d[x].max()]))

In [8]:
high

array([1.16994e+00, 1.16996e+00, 1.16834e+00, 1.16907e+00, 5.22800e+03])

In [9]:
d

                        Open     High      Low    Close  Volume
Date_Time
2018-07-11 17:00:00  1.16994  1.16996  1.16675  1.16738  4813.0
2018-07-11 18:00:00  1.16736  1.16826  1.16656  1.16744  4523.0
2018-07-11 19:00:00  1.16744  1.16778  1.16685  1.16698  2424.0
2018-07-11 20:00:00  1.16700  1.16766  1.16700  1.16743   941.0
2018-07-11 21:00:00  1.16729  1.16809  1.16709  1.16740  3740.0
2018-07-11 22:00:00  1.16742  1.16772  1.16728  1.16764  1333.0
2018-07-11 23:00:00  1.16764  1.16781  1.16721  1.16751   753.0
2018-07-12 00:00:00  1.16746  1.16787  1.16702  1.16730   966.0
2018-07-12 01:00:00  1.16730  1.16800  1.16720  1.16747  1576.0
2018-07-12 02:00:00  1.16750  1.16800  1.16721  1.16728  1005.0
2018-07-12 03:00:00  1.16725  1.16775  1.16713  1.16760   841.0
2018-07-12 04:00:00  1.16760  1.16838  1.16756  1.16824   956.0
2018-07-12 05:00:00  1.16820  1.16866  1.16779  1.16788  1367.0
2018-07-12 06:00:00  1.16788  1.16869  1.16717  1.16849  2750.0
2018-07-12 07:00:00  1.16850  1.16932  1.16740  1.16844  3995.0
2018-07-12 08:00:00  1.16845  1.16926  1.16728  1.16746  2808.0
2018-07-12 09:00:00  1.16747  1.16836  1.16692  1.16774  2741.0
2018-07-12 10:00:00  1.16774  1.16812  1.16606  1.16610  2948.0
2018-07-12 11:00:00  1.16610  1.16642  1.16496  1.16526  3224.0
2018-07-12 12:00:00  1.16528  1.16882  1.16528  1.16716  5228.0
2018-07-12 13:00:00  1.16722  1.16812  1.16671  1.16732  3689.0
2018-07-12 14:00:00  1.16733  1.16859  1.16691  1.16839  3844.0
2018-07-12 15:00:00  1.16842  1.16962  1.16784  1.16907  3288.0
2018-07-12 16:00:00  1.16912  1.16928  1.16810  1.16823  2219.0
2018-07-12 17:00:00  1.16823  1.16872  1.16700  1.16760  2297.0
2018-07-12 18:00:00  1.16760  1.16777  1.16694  1.16706  2293.0
2018-07-12 19:00:00  1.16706  1.16758  1.16664  1.16746  1647.0
2018-07-12 20:00:00  1.16743  1.16749  1.16693  1.16719   846.0
2018-07-12 21:00:00  1.16707  1.16718  1.16660  1.16690   749.0
2018-07-12 22:00:00  1.16684  1.16694  1.16550  1.16637  1841.0
2018-07-12 23:00:00  1.16632  1.16648  1.16586  1.16645   857.0
2018-07-13 00:00:00  1.16646  1.16697  1.16612  1.16670  1542.0
2018-07-13 01:00:00  1.16669  1.16754  1.16644  1.16686  1381.0
2018-07-13 02:00:00  1.16680  1.16740  1.16661  1.16697  1279.0
2018-07-13 03:00:00  1.16695  1.16695  1.16610  1.16616  1040.0
2018-07-13 04:00:00  1.16618  1.16660  1.16571  1.16572   791.0
2018-07-13 05:00:00  1.16575  1.16634  1.16542  1.16632   901.0
2018-07-13 06:00:00  1.16632  1.16632  1.16422  1.16461  2270.0
2018-07-13 07:00:00  1.16460  1.16504  1.16248  1.16306  4122.0
2018-07-13 08:00:00  1.16310  1.16366  1.16128  1.16268  3849.0
2018-07-13 09:00:00  1.16268  1.16380  1.16163  1.16352  3335.0
2018-07-13 10:00:00  1.16348  1.16376  1.16215  1.16242  2564.0
2018-07-13 11:00:00  1.16248  1.16348  1.16184  1.16266  2830.0
2018-07-13 12:00:00  1.16266  1.16465  1.16256  1.16450  3694.0
2018-07-13 13:00:00  1.16449  1.16484  1.16376  1.16414  3940.0
2018-07-13 14:00:00  1.16412  1.16693  1.16397  1.16669  4098.0
2018-07-13 15:00:00  1.16664  1.16726  1.16590  1.16664  3109.0
2018-07-13 16:00:00  1.16665  1.16777  1.16654  1.16736  1770.0
2018-07-13 17:00:00  1.16740  1.16758  1.16662  1.16758  1431.0
2018-07-13 18:00:00  1.16764  1.16832  1.16738  1.16772  1503.0
2018-07-13 19:00:00  1.16772  1.16843  1.16756  1.16814  1168.0
2018-07-13 20:00:00  1.16816  1.16873  1.16809  1.16858  1145.0
2018-07-15 21:00:00  1.16908  1.16934  1.16817  1.16856   605.0
2018-07-15 22:00:00  1.16854  1.16856  1.16784  1.16832   723.0
2018-07-15 23:00:00  1.16834  1.16834  1.16834  1.16834     1.0
2018-07-15 22:00:00  1.16854  1.16856  1.16784  1.16822   617.0

In [10]:
d['High'].max()

1.16996